swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /verify/{id}:
    get:
      operationId: "verifier.verify_toggle"
      tags:
        - "verifier"
      summary: "The reservation data structure supported by the server application"
      description: "Read the list of reservations"
      parameters:
        - in : path
          name: id
          type: "string"
          description: the toggle file name
          required: true
      responses:
        200:
          description: "Successful read reservation list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                day:
                  type: "string"
                booked:
                  type: "boolean"
#    post:
#      operationId: "reservations.create_reservation"
#      tags:
#        - "reservations"
#      summary: "The reservation data structure supported by the server application"
#      description: "Create a new reservation"
#      parameters:
#        - in : query
#          name: day
#          type: string
#          description: the reservation date
#          required: true
#      responses:
#        201:
#          description: "if operation is a success"
#          schema:
#            type: "string"
#  /reservations/{id}:
#    delete:
#      operationId: "reservations.delete_reservation"
#      tags:
#        - "reservations"
#      summary: "The reservation data structure supported by the server application"
#      description: "delete a reservation"
#      parameters:
#        - in : path
#          name: id
#          type: integer
#          description: the order id
#          required: true
#      responses:
#        204:
#          description: "if operation is a success"
#          schema:
#            type: "string"
#  /reservations/{id}/orders:
#    get:
#      operationId: "reservations.get_orders"
#      tags:
#        - "orders"
#      summary: "The order data structure supported by the server application"
#      description: "Read all orders for this reservation"
#      parameters:
#        - name: id
#          in: path
#          description: reservation id
#          type: integer
#          required: True
#      responses:
#        200:
#          description: "Successful read orders operation"
#          schema:
#            type: "array"
#            items:
#              properties:
#                reservation_id:
#                  type: "integer"
#                customer_name:
#                  type: "string"
#                customer_order:
#                  type: "string"
#    post:
#      operationId: "reservations.create_order"
#      tags:
#        - "orders"
#      summary: "The order data structure supported by the server application"
#      description: "Create a new order"
#      parameters:
#        - in : path
#          name: id
#          type: integer
#          description: the reservation id
#          required: true
#        - in : query
#          name: customer_name
#          type: string
#          description: the customer_name
#          required: true
#        - in : query
#          name: customer_order
#          type: string
#          description: the customer_order
#          required: true
#      responses:
#        201:
#          description: "if operation is a success"
#          schema:
#            type: "string"
#  /orders/{id}:
#    delete:
#      operationId: "reservations.delete_order"
#      tags:
#        - "orders"
#      summary: "The order data structure supported by the server application"
#      description: "delete an order"
#      parameters:
#        - in : path
#          name: id
#          type: integer
#          description: the order id
#          required: true
#      responses:
#        204:
#          description: "if operation is a success"
#          schema:
#            type: "string"